# Generated by Django 6.0.3 on 2026-03-31 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_content_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyversion',
            name='description',
        ),
        migrations.AddField(
            model_name='storyversion',
            name='text_en',
            field=models.TextField(default='', verbose_name='İngilizce Metin'),
        ),
        migrations.AddField(
            model_name='storyversion',
            name='text_tr',
            field=models.TextField(default='', verbose_name='Türkçe Metin'),
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('word_type', models.CharField(help_text='Örn: n., v., adj.', max_length=50)),
                ('meaning', models.CharField(max_length=200)),
                ('example_sentence', models.TextField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='stories.storyversion')),
            ],
        ),
    ]
