# Generated by Django 6.0.3 on 2026-04-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_remove_storyversion_description_storyversion_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cast',
            field=models.TextField(blank=True, help_text='Virgülle ayır. Örn: Bryan Cranston, Aaron Paul', verbose_name='Oyuncular'),
        ),
        migrations.AddField(
            model_name='content',
            name='developer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Geliştirici'),
        ),
        migrations.AddField(
            model_name='content',
            name='director',
            field=models.CharField(blank=True, max_length=200, verbose_name='Yönetmen'),
        ),
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.CharField(blank=True, help_text='Film için. Örn: 2s 22dk', max_length=50, verbose_name='Süre'),
        ),
        migrations.AddField(
            model_name='content',
            name='season_count',
            field=models.CharField(blank=True, help_text='Sadece dizi için. Örn: 5 Sezon', max_length=50, verbose_name='Sezon Sayısı'),
        ),
        migrations.AddField(
            model_name='content',
            name='studio',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stüdyo'),
        ),
        migrations.AddField(
            model_name='content',
            name='year',
            field=models.CharField(blank=True, help_text='Örn: 2008 veya 2008-2013', max_length=20, verbose_name='Yıl'),
        ),
    ]
