# Generated by Django 6.0.3 on 2026-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('movie', 'Film'), ('series', 'Dizi'), ('game', 'Oyun'), ('animation', 'Çizgi Film')], default='series', max_length=20)),
                ('level', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField()),
                ('poster_url', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
