# Generated by Django 6.0.3 on 2026-03-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_content_delete_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='description',
        ),
        migrations.RemoveField(
            model_name='content',
            name='level',
        ),
        migrations.RemoveField(
            model_name='content',
            name='rating',
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('movie', 'Film'), ('series', 'Dizi'), ('game', 'Oyun')], max_length=20),
        ),
        migrations.CreateModel(
            name='StoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=5)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='stories.content')),
            ],
            options={
                'unique_together': {('content', 'level')},
            },
        ),
    ]
