# Generated by Django 6.0.3 on 2026-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_content_description_remove_content_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('movie', 'Film'), ('series', 'Dizi'), ('game', 'Oyun'), ('animation', 'Animasyon')], max_length=20),
        ),
    ]
