# Generated by Django 6.0.3 on 2026-04-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_content_cast_content_developer_content_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='cast',
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Süre'),
        ),
        migrations.AlterField(
            model_name='content',
            name='season_count',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sezon Sayısı'),
        ),
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Yıl'),
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Oyuncu Adı')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Rol Adı')),
                ('photo_url', models.CharField(blank=True, max_length=500, verbose_name='Fotoğraf URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='stories.content')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
