# Generated by Django 6.0.3 on 2026-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_remove_content_cast_alter_content_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyversion',
            name='rating',
        ),
        migrations.AddField(
            model_name='content',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Puan'),
        ),
    ]
