# Generated by Django 6.0.4 on 2026-04-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_remove_storyversion_rating_content_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.CharField(blank=True, help_text='Örn: Dram, Aksiyon, Suç', max_length=100, verbose_name='Tür'),
        ),
    ]
