# Generated by Django 6.0.4 on 2026-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_content_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Kelime')),
                ('word_type', models.CharField(blank=True, max_length=50, verbose_name='Kelime Türü')),
                ('meaning_tr', models.CharField(blank=True, max_length=300, verbose_name='Türkçe Anlam')),
                ('definition_en', models.TextField(blank=True, verbose_name='İngilizce Tanım')),
                ('example_sentence', models.TextField(blank=True, verbose_name='Örnek Cümle')),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=5, verbose_name='Seviye')),
                ('phonetic', models.CharField(blank=True, max_length=100, verbose_name='Telaffuz')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
